[package]
name = "aurora_drivers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
spin.workspace = true
lazy_static.workspace = true
bitflags.workspace = true
log.workspace = true

# PCI access
pci_types = "0.8"

# Optional: for hardware access
x86_64 = { version = "0.14", default-features = false, optional = true }

[features]
default = ["hw_access"]
hw_access = ["dep:x86_64"]
